server:
  port: 8080
  servlet:
    context-path: /
com:
  example:
    demo-apps:
      account-service:
        endpoint: http://account-service:8080/api/v1/account
      order-service:
        endpoint: http://order-service:8080/api/v1/order
