server:
  port: 8081
  servlet:
    context-path: /
com:
  example:
    demo-apps:
      account-service:
        endpoint: http://localhost:8082/api/v1/account
      order-service:
        endpoint: http://localhost:8083/api/v1/order
